services:
  postgres:
    image: postgres:17
    container_name: white-board-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: Vp2hPj8Z
      POSTGRES_DB: white-board
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
    volumes:
      - white-board-db:/var/lib/postgresql/data

volumes:
  white-board-db:
